name: Check

on:
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

env:
  COMPOSER_ROOT_VERSION: 0.4.x-dev

jobs:
  composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer validate
      - run: composer normalize --dry-run
      - run: composer check-require
      - run: composer check-unused

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer fixcs -- --dry-run --format=checkstyle

  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dependency-versions: [locked, lowest, highest]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependency-versions }}
      - run: composer psalm -- --stats --output-format=github ${{ matrix.dependency-versions == 'locked' && '--shepherd' || '' }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2, 8.3, 8.4]
        dependency-versions: [locked, lowest, highest]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-file: development
          tools: composer:v2
          coverage: ${{ matrix.php == '8.1' && matrix.dependency-versions == 'locked' && 'pcov' || '' }}
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
          dependency-versions: ${{ matrix.dependency-versions }}
      - run: composer test -- --colors=always --coverage-clover=coverage.xml ${{ matrix.php == '8.4' && '--testsuite=php84' || '' }}
      - if: ${{ matrix.php == '8.1' && matrix.dependency-versions == 'locked' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  infection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          ini-file: development
          tools: composer:v2
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
